apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k3d-tst
  namespace: k3d-tst
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi # 去瓜分 PV 的資源 (或寫 0.5Gi)